/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114971-g1b41631185-20240423"
#endif /* AVUTIL_FFVERSION_H */
